name: Terraform CI/CD

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3  # Atualizando para a versão 3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Atualizando para a versão 2
        with:
          terraform_version: 1.3.5 

      - name: Terraform Init
        run: terraform init
        working-directory: ./ec2  # Definindo o diretório de trabalho

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./ec2  # Definindo o diretório de trabalho
        env:  # Passando as variáveis de ambiente para o Terraform
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./ec2  # Definindo o diretório de trabalho
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
