name: Terraform CI/CD

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5 

      - name: Terraform Init
        run: terraform init
        working-directory: ./ec2  

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./ec2  

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./ec2  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Referência ao secret
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Referência ao secret
